异常处理
---
- try catch 只能用于同步执行的代码。异常会沿着代码执行路径一路冒泡，直到遇到一个try语句被捕获。异步函数（如setTimeout）会打断代码执行路径，异步函数执行过程中产生的异常冒泡到执行路径被打断的位置时，如果一直没有遇到try语句，就作为全局异常抛出。
- 所以要在异常冒泡到断点之前用try语句捕获异常，并通过回调函数传递被捕获的异常。比如在异步函数开始就用。
- 因此nodejs回调函数第一个参数都是err。
- 如果回调函数嵌套多了，异常处理也得每层都放进去，就很丑。
- nodejs的解决方案是域Domain，可以简化异步代码的异常处理。